---
- name: Restauration MikroTik depuis FTP
  hosts: all
  gather_facts: no
  vars:
    ftp_address: "192.168.100.100"
    ftp_user: "ftpuser"
    ftp_password: "Marsouk57"
    rsc_file_name: "mikrotik_0C-D8-E1-9D-00-00_2025-06-21_16-06-41.rsc"

  tasks:
    - name: Télécharger le fichier RSC
      community.routeros.command:
        commands:
          - >
            /tool fetch address={{ ftp_address }}
            src-path={{ rsc_file_name }}
            user={{ ftp_user }}
            password={{ ftp_password }}
            mode=ftp
            dst-path={{ rsc_file_name }}
            upload=no
      register: fetch_result
      retries: 3
      delay: 5

    - name: Importer la configuration
      community.routeros.command:
        commands:
          - /import file-name={{ rsc_file_name }}
      register: import_result
