# Fichier généré le 2025-06-26_15-13-11
# Sous-réseau: 192.168.20.0/24
# Serveur FTP: 192.168.20.3


[ciscoios]
CA-02-C9-B8-00-1C ansible_host=192.168.20.6 ansible_user=admin ansible_ssh_pass=Cisco2025 ansible_network_os=cisco.ios.ios ansible_connection=network_cli