---
# Playbook FortiGate - Généré le 2025-07-02_23-45-46
- name: Sauvegarder la configuration FortiGate via FTP
  hosts: fortinet
  gather_facts: no
  tasks:
    - name: Backup config via raw command
      ansible.builtin.raw: >
        execute backup config ftp fortinet_{{ inventory_hostname }}_{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}.cfg
        192.168.20.3
        ftpuser
        Ftpuser57
