---
- name: Restauration Cisco depuis FTP
  hosts: all
  gather_facts: yes
  vars:
    ftp_server: "192.168.10.3"
    ftp_username: "ftpuser"
    ftp_password: "Marsouk57"
    config_file: "cisco_ios_CA-01-3F-7D-00-1C_2025-07-02_22-33-10.cfg"

  tasks:
    - name: Copier la configuration depuis FTP
      cisco.ios.ios_command:
        commands:
          - "copy ftp://{{ ftp_username }}:{{ ftp_password }}@{{ ftp_server }}/{{ config_file }} startup-config\n\n"
      register: result
      ignore_errors: yes

    - name: Appliquer la configuration
      cisco.ios.ios_command:
        commands:
          - "copy startup-config running-config\n\n"
      when: not result.failed
      ignore_errors: yes
