# Fichier généré le 2025-06-26_15-13-11
# Sous-réseau: 192.168.10.0/24
# Serveur FTP: 192.168.10.3


[ciscoios]
AA-BB-CC-80-01-00 ansible_host=192.168.10.1 ansible_user=admin ansible_ssh_pass=Cisco2025 ansible_network_os=cisco.ios.ios ansible_connection=network_cli ansible_become=yes ansible_become_method=enable ansible_become_password=Cisco2025
CA-01-3F-7D-00-1C ansible_host=192.168.10.6 ansible_user=admin ansible_ssh_pass=Cisco2025 ansible_network_os=cisco.ios.ios ansible_connection=network_cli
AA-BB-CC-80-02-00 ansible_host=192.168.10.2 ansible_user=admin ansible_ssh_pass=Cisco2025 ansible_network_os=cisco.ios.ios ansible_connection=network_cli ansible_become=yes ansible_become_method=enable ansible_become_password=Cisco2025